version: '3.8'
services:
  app:
    build:
      context: .
    container_name: texttosql-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: streamlit run frontend/app.py --server.port=8501 --server.address=0.0.0.0
